name: Second workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: qo girtsy chi
        run: |
          echo "some text" >> text.txt
          ls
          pwd
          echo "${{ toJSON(github) }}"
